name: Continuous Integration

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - run: npm ci
        shell: sh

      - run: npm run lint
        shell: sh

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - run: npm ci
        shell: sh

      - run: npm run e2e
        shell: sh
